name: MacOS
on: 
  push:
  pull_request:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: macOS-latest
    strategy:
      matrix:
        node-version: [16, 18, 20, 22]
        architecture: [x64, arm64]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        architecture: ${{ matrix.architecture }}

    - name: Build using specified architecture
      run: |
        case "${{ matrix.architecture }}" in
          x64)
            arch -x86_64 npm i
            arch -x86_64 npm test
            ;;
          arm64)
            arch -arm64 npm i
            arch -arm64 npm test
            ;;
        esac